<a href="https://colab.research.google.com/github/mwangi2145/PyTorch-Tutorial-YOUtube/blob/main/Tensors%2C_List_and_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

LIST

In [3]:
my_list =[1,2,3,4,5],[6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

NUMPY ARRAYS

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.35155659, 0.30347055, 0.59464454, 0.61172359],
       [0.33060585, 0.10017167, 0.80536824, 0.68256949],
       [0.04058562, 0.56219619, 0.70455391, 0.41804817]])

In [5]:
np1.dtype

dtype('float64')

TENSORS

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.2615,  0.6210,  0.0309,  0.2518],
        [-0.4366, -0.5742, -0.1083,  0.0514],
        [ 0.7060, -0.0693,  0.7417,  0.2285]])

In [14]:
tensor_2d =torch.zeros(3,4)
tensor_2d
##tensor_2d.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
tensor_3d =torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## creat tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3516, 0.3035, 0.5946, 0.6117],
        [0.3306, 0.1002, 0.8054, 0.6826],
        [0.0406, 0.5622, 0.7046, 0.4180]], dtype=torch.float64)